name: dependnecy submission

on:
    push:


jobs:
    submit:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: CocoaPods Dependency Submission Action
            uses: advanced-security/cocoapods-dependency-submission-action@v1.0
            with:
                cocoapods-lock: './packages/rn-tester/Podfile.lock'